### ISSUE TITLE
Build Kernel for Enuma

### ISSUE THREAD

**Issue by alghiffaryfa19** [HuaJI66/Xiaomi_Kernel_OpenSource#8]
I try to build for enuma, but error like this, do you know what i should do ?
![image](https://github.com/user-attachments/assets/69fe4434-e413-434b-b634-34c6408b3d5f)

**Comment by HuaJI66** [comment]
If the Image file is not successfully compiled in the out/arch/arm64/boot directory, you can delete the out directory and recompile it.

```
cd "repository  directory" 
rm -rf out
```

**Comment by alghiffaryfa19** [comment]
[error.log](https://github.com/user-attachments/files/17778372/error.log)
error log, I don't really know what's wrong

**Comment by HuaJI66** [comment]
Need to install python2 manually.
```shell
## python2
wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
sudo tar xzf Python-2.7.18.tgz
cd Python-2.7.18
sudo ./configure --enable-optimizations
sudo make altinstall
sudo ln -sfn '/usr/local/bin/python2.7' '/usr/bin/python2'
```
![Screenshot_2024-11-16-23-35-12-468_bin mt plus-edit](https://github.com/user-attachments/assets/1ae1e685-60ba-46f8-94a3-c0479ebbe5ec)
